name: Build Mod

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        default: CreateNuclear
        description: Mod file name
      version:
        required: true
        description: Mod version (ex: 1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build Mod
        run: ./gradlew clean build

      - name: Rename Output Jar
        run: |
          mkdir renamed
          FILE=$(find build/libs -name "*.jar" | grep -v sources | head -n 1)
          echo "Found jar: $FILE"
          cp "$FILE" "renamed/${{ github.event.inputs.name }}-${{ github.event.inputs.version }}.jar"
          ls renamed/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Renamed-Jar
          path: renamed/
