# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        required: false
        description: Version mod Create Nuclear to release 

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: build
        run: ./gradlew build
      
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      
      - name: Release
        id: release
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          VERSION=`${{github.event.inputs.minecraft_version}}`
          git tag -a $VERSION -m "version du mod"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Push Tag
        run: git push --follow-tags
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "build/libs/*.jar"
          tag: ${{ steps.release.outputs.VERSION }}
